spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/admin
      database: ${MONGO_DATABASE}

security:
  jwt:
    access-key: ${ACCESS_KEY}
    plugin-key: ${PLUGIN_KEY}

path:
  downloads: /downloads
  uploads: /uploads